name: Build Windows Game
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Haxe
        uses: krdlab/setup-haxe@v2
        with:
          haxe-version: 4.2.5

      - name: Install Haxelib Packages
        run: |
          haxelib install lime 8.1.2 --never
          haxelib install openfl 9.3.3 --never
          haxelib install flixel 5.6.1 --never
          haxelib install flixel-addons 3.2.2 --never
          haxelib install flixel-tools 1.5.1 --never
          haxelib install flixel-ui 2.5.0 --never
          haxelib install hscript 2.5.0 --never
          haxelib install hscript-iris 1.1.3 --never
          haxelib install tjson 1.4.0 --never
          haxelib install hxdiscord_rpc 1.2.4 --never

      - name: Install Git Libraries
        run: |
          haxelib git SScript https://github.com/YoshiCrafter29/SScript
          haxelib git flxanimate https://github.com/ShadowMario/flxanimate
          haxelib git linc_luajit https://github.com/superpowers04/linc_luajit
          haxelib git hxCodec https://github.com/polybiusproxy/hxCodec
          haxelib git hxdiscord https://github.com/MA3A/hxdiscord
          haxelib git hscript-ex https://github.com/ianhatcher/hscript-ex
          haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc
          haxelib run lime setup -y

      - name: Patch HScript for Haxe 4.2.5
        run: |
          python -c "
          path = 'source/psychlua/HScript.hx'
          with open(path, 'r', encoding='utf-8') as f:
              lines = f.readlines()
          print('Original:', lines[431])
          lines[431] = lines[431].replace('?.', '.')
          with open(path, 'w', encoding='utf-8') as f:
              f.writelines(lines)
          print('¡Parche aplicado con éxito!')
          "

      - name: Build Game
        run: haxelib run lime build windows -release

      - name: Upload Executable Artifact
        uses: actions/upload-artifact@v4
        with:
          name: FNF-PsychEngine-Windows
          path: export/release/windows/bin/
