name: Build Windows Game
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Haxe
        uses: krdlab/setup-haxe@v2
        with:
          haxe-version: 4.3.2

      - name: Install All Dependencies
        run: |
          haxelib install lime --never
          haxelib install openfl --never
          haxelib install flixel --never
          haxelib install flixel-addons --never
          haxelib install flixel-tools --never
          haxelib install flixel-ui --never
          haxelib install hscript --never
          haxelib install hscript-iris --never
          haxelib install tjson --never
          haxelib install SScript --never
          haxelib git linc_luajit https://github.com/superpowers04/linc_luajit --never
          haxelib git hxCodec https://github.com/polybiusproxy/hxCodec --never
          haxelib git hxdiscord https://github.com/MA3A/hxdiscord --never
          haxelib git hscript-ex https://github.com/ianhatcher/hscript-ex --never
          haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc --never
          haxelib run lime setup -y

      - name: Build Game
        run: haxelib run lime build windows -release

      - name: Upload Executable Artifact
        uses: actions/upload-artifact@v4
        with:
          name: FNF-PsychEngine-Windows
          path: export/release/windows/bin/
